name: Build and deploy IG

on:
  push:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tabs      
  workflow_dispatch:    

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache contents of ~/.fhir for docker volume
        id: fhir-cache
        uses: actions/cache@v3
        with:
          path: /.fhir
          key: ${{ runner.os }}-fhir
          
      - name: Cache input-cache directory
        id: input-cache
        uses: actions/cache@v3
        with:
          path: ./input-cache
          key: ${{ runner.os }}-input-cache       
          
      - name: Update the image to the latest publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: _updatePublisher.sh --yes
          
      - name: Run the IG publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: java -jar ./input-cache/publisher.jar publisher -ig .            

      # if it is the main branch, deploy to main directory
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }} 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          # keeps gh-pages branch from storing old commits, which balloons size of repo
          force_orphan: true

      # deploy output to sub-directory indicated by the tag or branch that triggered this workflow, used for testing only
      # triggered manually by dispatch of selected branch
      # will be overwritten with next deployment to main
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref != 'refs/heads/main' }} 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          destination_dir: ${{ github.ref_name }}
          keep_files: true